### PR TITLE
Fix Bug #78321 Fix typo in function name (cenral -> central)

### PR DESCRIPTION
**Pull request by Girgias**
Function name was incorrect and had a typo.

### CODE REVIEW

**Comment by cmb69** [comment]
Hmm, fixing a typo in a function name would constitute a BC break.

Anyhow, @y-uti, could you please have a look at this PR?

**Comment by Girgias** [comment]
> Hmm, fixing a typo in a function name would constitute a BC break.

I'd suppose because this is a PECL extension this change could be tagged into a new major version?

**Comment by y-uti** [comment]
How about we also keep the old function but mark as deprecated?

**Comment by Girgias** [comment]
> 
> 
> How about we also keep the old function but mark as deprecated?

Could always do that, is there a way to mark a function a deprecated alias?

**Comment by cmb69** [comment]
> Could always do that, is there a way to mark a function a deprecated alias?

PHP_DEP_FALIAS

**Comment by y-uti** [comment]
@Girgias Would you add PHP_DEP_FALIAS entry for stats_rand_gen_noncenral_f function?

**Comment by Girgias** [comment]
Yes will do sorry was busy this week let me do that just now.

**Comment by Girgias** [comment]
@y-uti Done :)

**Pull request merged**
